#ifndef SIGN_H
#define SIGN_H
#define SUCCESS_STATUS 0
#define FAIL_STATUS 1
#define PENDING_STATUS 2
#define OTHER_THREAD_IS_PROCESSING_STATUS 3
#define GET_LOCK_FAIL_STATUS 4
#define RELEASE_LOCK_FAIL_STATUS 5
#define WILL_DEL_STATUS 6
#endif